# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    yarn install
  displayName: 'Install Dependencies'

- script: |
    yarn test:cov
  displayName: 'Run Tests'

- task: PublishTestResults@2
  displayName: 'Publish Test Results'
  inputs:
    testResultsFiles: '**junit*.xml'
    testRunTitle: TestRun ${{ parameters.name }} $(node_version)

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage results'
  inputs:
    codeCoverageTool: 'cobertura'
    summaryFileLocation: '**/coverage/cobertura-coverage.xml'
